### ISSUE TITLE
Installing packages on pyraf 

### ISSUE THREAD

**Issue by mrkendurkar** [iraf-community/pyraf#147]
Hello, 

I was wondering if there is any way that we could install a custom external package in Pyraf which is running on a Linux machine?

Thanks in advance!

**Comment by olebole** [comment]
I am not sure what exactly you are trying to do. What is a "custom external package in Pyraf"? Is it somewhere available? Which IRAF and PyRAF versions did you install, and on which platform?

**Comment by mrkendurkar** [comment]
I have installed 2.1.15 PyRAF version on a Linux Machine. 

 Sorry about the confusion about the package. 
My colleague and I wrote a new package for our observatory and we are trying to import that package.

**Comment by olebole** [comment]
> __Warning__ First, I would really suggest to *not* write new packages for IRAF/PyRAF. The IRAF ecosystem is clearly deprecated, there is no institutional support, and knowledge about it is going away. Starting a new package is anything else than future proof.

Then, what version of IRAF do you use? Older versions (before 2.17) have quite a number of bugs and are not recommended. Also, PyRAF 2.1.15 is quite old and has a number of bugs; can you consider switching to the recent 2.2.1 (which would also support Python 3 instead of Python 2 which is End Of Life)?

Finally, how does the package look like and what exactly did you to "import that package"? Is it a Python package? Then, an `import mypackage` should work if the package is installed correctly within your `PYTHONPATH`. If it is an IRAF package, where did you put it, and what did you configure to get it imported?

**Comment by mrkendurkar** [comment]
No, it's not a relevant issue anymore. 

 Thanks for the help!
