### ISSUE TITLE
Incompatible with numpy 2.0

### ISSUE THREAD

**Issue by LHe496** [iraf-community/pyraf#172]
In numpy 2.0, it is not allowed to convert out-of-bound Python integers to integer arrays. In numpy 1.26.4, it is just a deprecation warning. The code influenced by such change that I found so far is the '__init__' method for class  'IrafHatchFills' in file gki.py, which causes an error when using splot in pyraf.

It is recommanded by numpy to use 'np.array(value).astype(dtype)' rather than simply convert it to an array.

![截图 2024-07-31 17-14-35](https://github.com/user-attachments/assets/642d1276-06e0-4f0d-b51c-2e19aab5a883)

using the way numpy recommanded:
![image](https://github.com/user-attachments/assets/78efb569-8cd9-40bd-b084-f43d96cee8f6)

**Comment by olebole** [comment]
When follwoing the use of **IrafHatchFills** in PyRAF, it looks that the only place is in the initialization of kiInteractiveTkBase: https://github.com/iraf-community/pyraf/blob/151350f040c0b7fb770c65d68c07b5979523ec6e/pyraf/gkitkbase.py#L205-L212

The attribute **hatchfills** is then never references within the PyRAF code base. The only reference I could find is in `gkiopengl.py`; however there it was always commented out (since its introduction before 2000): https://github.com/iraf-community/pyraf/blob/5f6f68df0a0f9e78f0717716ff9afc59f325a59f/lib/gkiopengl.py#L360-L371

This was however removed in 70b0404 2008.

**hatchfills** is also not part of a Tcl/Tk interface, so I doubt it has any use; I think we can simply remove this attribute and the **IrafHatchFills** class. It was probably just forgotten when the OpenGL kernel was removed.
