### ISSUE TITLE
No interactive display of pyraf 

### ISSUE THREAD

**Issue by rjoebruch** [iraf-community/pyraf#173]
Hi! 
I am currently trying to install and run the new pessto pipeline (see here: https://github.com/svalenti/pessto ) with a M2 Mac with OS Ventura 13.12
I created a virtual environment with python 3.7 as instructed through the pipeline. After several issues (see here: https://github.com/iraf-community/pyraf/issues/103 and a quick fix which requires that after the iraf setup in my bash profile, I need to redefine my commands for bash and the IRAFARCH as empty , like this :
```
#### IRAF shortcut
export PATH='/usr/local/lib/iraf/bin/:$PATH'
export iraf='/usr/local/lib/iraf/'


# Add iraf setup commands
if [ -e /Users/r.olivaw/.iraf/setup.sh ]; then
    source /Users/r.olivaw/.iraf/setup.sh
fi

export IRAFARCH=''
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
 
```
)

I now cannot use the interactive plot. Whenever I run the pipeline, a python window open, remains blank and the cursor just spins over it (see screenshot) 

![Screenshot 2024-08-07 at 13 26 59](https://github.com/user-attachments/assets/46f7c810-74a3-4878-8704-6858c273ab3d)

I already set the `~/.matplotlib/matplotlibrc` to be `backend : TKAgg` or `backend : macosx` but this does not solve the problem. 

The matplotlib version that I have installed is: 3.5.3

Thank you!

**Comment by olebole** [comment]
As I am not a PESSTO user: could you please create a minimal self-contained example, i.e. all input data and the exact **APALL** call that reqproduces this behaviour?

----

BTW, for the community version of IRAF you should ***not*** call `~/.iraf/setup.sh`, i.e. you should ***remove*** the lines
```shell
# Add iraf setup commands
if [ -e /Users/r.olivaw/.iraf/setup.sh ]; then
    source /Users/r.olivaw/.iraf/setup.sh
fi
```
They do the setup for the old NOAO IRAF versions with settings that may not work for the community version. I would also not just add everything you know to the **PATH** environment variable. Usually, **PATH** already contains the standard directories like `/bin` or `/usr/bin`; one only needs to add local specialities. And `/usr/local/lib/iraf/bin/` should not be in the **PATH** because there are no directly user-callable functions in (what is user callable is linked in `/usr/local/bin/`).

**Comment by rjoebruch** [comment]
Thank you!
We found the functions and the bugs: it turns out that the way this pipeline is written you need to press enter 3 times until it displays the iraf graphs.
